// Code generated by "string-enumer -t PolicyType -o ./generated.go ."; DO NOT EDIT.
package policytype

// validPolicyTypeValues contains a map of all valid PolicyType values for easy lookup
var validPolicyTypeValues = map[PolicyType]struct{}{
	TargetConnect:        {},
	OrganizationControls: {},
	SessionRecording:     {},
	Kubernetes:           {},
	Proxy:                {},
	JustInTime:           {},
}

// Valid validates if a value is a valid PolicyType
func (v PolicyType) Valid() bool {
	_, ok := validPolicyTypeValues[v]
	return ok
}

// PolicyTypeValues returns a list of all (valid) PolicyType values
func PolicyTypeValues() []PolicyType {
	return []PolicyType{
		TargetConnect,
		OrganizationControls,
		SessionRecording,
		Kubernetes,
		Proxy,
		JustInTime,
	}
}
