// Code generated by "string-enumer -t TargetStatus -o ./generated.go ."; DO NOT EDIT.
package targetstatus

// validTargetStatusValues contains a map of all valid TargetStatus values for easy lookup
var validTargetStatusValues = map[TargetStatus]struct{}{
	NotActivated: {},
	Offline:      {},
	Online:       {},
	Terminated:   {},
	Error:        {},
	Restarting:   {},
}

// Valid validates if a value is a valid TargetStatus
func (v TargetStatus) Valid() bool {
	_, ok := validTargetStatusValues[v]
	return ok
}

// TargetStatusValues returns a list of all (valid) TargetStatus values
func TargetStatusValues() []TargetStatus {
	return []TargetStatus{
		NotActivated,
		Offline,
		Online,
		Terminated,
		Error,
		Restarting,
	}
}
