changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} ({{.Time.Format "January 02, 2006"}})'
kindFormat: '{{.Kind}}:'
changeFormat: '* {{.Body}} ([#{{.Custom.Issue}}](https://github.com/bastionzero/bastionzero-sdk-go/issues/{{.Custom.Issue}})).'
custom:
  - key: Issue
    label: Issue/PR Number
    type: int
    minInt: 1
kinds:
  - label: BREAKING CHANGES
    auto: major
  - label: FEATURES
    auto: minor
  - label: ENHANCEMENTS
    auto: minor
  - label: NOTES
    auto: patch
  - label: BUG FIXES
    auto: patch
newlines:
  afterKind: 1
  beforeKind: 1
  endOfVersion: 2
