// Code generated by "string-enumer -t DynamicAccessConfigurationStatus -o ./generated.go ."; DO NOT EDIT.
package dacstatus

// validDynamicAccessConfigurationStatusValues contains a map of all valid DynamicAccessConfigurationStatus values for easy lookup
var validDynamicAccessConfigurationStatusValues = map[DynamicAccessConfigurationStatus]struct{}{
	DACOffline: {},
	DACOnline:  {},
}

// Valid validates if a value is a valid DynamicAccessConfigurationStatus
func (v DynamicAccessConfigurationStatus) Valid() bool {
	_, ok := validDynamicAccessConfigurationStatusValues[v]
	return ok
}

// DynamicAccessConfigurationStatusValues returns a list of all (valid) DynamicAccessConfigurationStatus values
func DynamicAccessConfigurationStatusValues() []DynamicAccessConfigurationStatus {
	return []DynamicAccessConfigurationStatus{
		DACOffline,
		DACOnline,
	}
}
