// Code generated by "string-enumer -t DATState -o ./generated.go ."; DO NOT EDIT.
package datstate

// validDATStateValues contains a map of all valid DATState values for easy lookup
var validDATStateValues = map[DATState]struct{}{
	Starting:   {},
	Started:    {},
	StartError: {},
	Stopping:   {},
	Stopped:    {},
	StopError:  {},
}

// Valid validates if a value is a valid DATState
func (v DATState) Valid() bool {
	_, ok := validDATStateValues[v]
	return ok
}

// DATStateValues returns a list of all (valid) DATState values
func DATStateValues() []DATState {
	return []DATState{
		Starting,
		Started,
		StartError,
		Stopping,
		Stopped,
		StopError,
	}
}
