// Code generated by "string-enumer -t TargetNameOption -o ./generated.go ."; DO NOT EDIT.
package targetnameoption

// validTargetNameOptionValues contains a map of all valid TargetNameOption values for easy lookup
var validTargetNameOptionValues = map[TargetNameOption]struct{}{
	Timestamp:            {},
	DigitalOceanMetadata: {},
	AwsEc2Metadata:       {},
	BashHostName:         {},
}

// Valid validates if a value is a valid TargetNameOption
func (v TargetNameOption) Valid() bool {
	_, ok := validTargetNameOptionValues[v]
	return ok
}

// TargetNameOptionValues returns a list of all (valid) TargetNameOption values
func TargetNameOptionValues() []TargetNameOption {
	return []TargetNameOption{
		Timestamp,
		DigitalOceanMetadata,
		AwsEc2Metadata,
		BashHostName,
	}
}
