// Code generated by "string-enumer -t TargetType -o ./generated.go ."; DO NOT EDIT.
package targettype

// validTargetTypeValues contains a map of all valid TargetType values for easy lookup
var validTargetTypeValues = map[TargetType]struct{}{
	Bzero:               {},
	Cluster:             {},
	DynamicAccessConfig: {},
	Web:                 {},
	Db:                  {},
}

// Valid validates if a value is a valid TargetType
func (v TargetType) Valid() bool {
	_, ok := validTargetTypeValues[v]
	return ok
}

// TargetTypeValues returns a list of all (valid) TargetType values
func TargetTypeValues() []TargetType {
	return []TargetType{
		Bzero,
		Cluster,
		DynamicAccessConfig,
		Web,
		Db,
	}
}
