name: release

on:
  push:
    branches: [ master ]
    paths: [ CHANGELOG.md ]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get the latest version
      id: latest
      uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23 # v2.0.0
      with:
        version: latest
        args: latest

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ".changes/${{ steps.latest.outputs.output }}.md"
        tag_name: "${{ steps.latest.outputs.output }}"
        draft: true